services:
  redis-bytebuild:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DATABASES=1
    volumes:
      - ./redis:/data

  postgres-bytebuild:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
